language: java
sudo: false
cache:
  directories:
    - $HOME/.m2/repository

jdk:
  - oraclejdk8
install: /bin/true
script:
  - mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
  - jdk_switcher use openjdk7
  - mvn test
notifications:
  email: false